export const examNames = [
  // 🧠 Most Popular Competitive Exams
  "UPSC Civil Services (IAS, IPS, IFS)",
  "SSC CGL",
  "Bank PO (IBPS, SBI, RBI)",
  "Railway Recruitment Board (RRB NTPC, Group D)",
  "UPSC NDA / CDS",
  "State PSC (UPPSC, BPSC, MPPSC, etc.)",
  "GATE",
  "CAT (Common Admission Test)",
  "UGC NET",
  "CTET / TET",

  // 🧪 Engineering & Technical Entrance
  "JEE Main",
  "JEE Advanced",
  "BITSAT",
  "VITEEE",
  "SRMJEEE",
  "KIITEE",
  "COMEDK UGET",
  "AMITY JEE",
  "IPU CET",
  "MU OET (Manipal Entrance Test)",

  // 🧬 Medical Entrance
  "NEET UG",

  // 🎓 University & College Entrance
  "CUET (Common University Entrance Test)",
  "DUET (Delhi University Entrance Test)",
  "BHU UET / PET",
  "Jamia Millia Islamia Entrance",
  "TISSNET",
  "Symbiosis SET",
  "Christ University Entrance Test",
  "Lovely Professional University NEST (LPUNEST)",

  // 🧾 State Board Exams (10th & 12th)
  "CBSE Board (10th / 12th)",
  "ICSE Board (10th / 12th)",
  "UP Board (10th / 12th)",
  "Bihar Board (BSEB 10th / 12th)",
  "Maharashtra Board (SSC / HSC)",
  "West Bengal Board (WBBSE / WBCHSE)",
  "Tamil Nadu Board (SSLC / HSC)",
  "Karnataka Board (SSLC / PUC)",
  "Gujarat Board (GSEB 10th / 12th)",
  "Rajasthan Board (RBSE 10th / 12th)",
  "Madhya Pradesh Board (MPBSE 10th / 12th)",
  "Odisha Board (BSE / CHSE)",
  "Punjab Board (PSEB 10th / 12th)",
  "Kerala Board (SSLC / DHSE)",
  "Telangana Board (SSC / Intermediate)",
  "Andhra Pradesh Board (BSEAP / BIEAP)",
  "Haryana Board (HBSE 10th / 12th)",
  "Chhattisgarh Board (CGBSE 10th / 12th)",
  "Jharkhand Board (JAC 10th / 12th)",
  "Assam Board (SEBA / AHSEC)",

  // 🧰 Government & Public Sector Jobs
  "DRDO Scientist Exam",
  "ISRO Scientist Exam",
  "IES (Indian Engineering Services)",
  "Indian Air Force (AFCAT)",
  "Indian Navy Exam",
  "EPFO Assistant / SSA",
  "FCI Exam",
  "SSC JE",
  "RRB JE / SSE",
  "LIC AAO / ADO",

  // 💼 Company/IT-Based Exams
  "TCS NQT",
  "Wipro Elite NTH",
  "Infosys InfyTQ",
  "Cognizant GenC",
  "Accenture ASE",
  "Tech Mahindra",
  "Capgemini",
  "Mindtree",
  "HCL TechBee",
  "IBM CodeKnack",
  "Amazon WOW",
  "Google Kickstart",
  "CodeVita",
  "Flipkart GRiD",
  "L&T Infotech",
  "Deloitte",
  "Virtusa",
  "Tata Elxsi",
  "Zensar",
  "DXC Technology",
];

export const types = ["Competition", "University", "Technical", "Aptitude"];
